cp template op_ADC.v
cp template op_ADD.v
cp template op_AND.v
cp template op_ASL.v
cp template op_BBR.v
cp template op_BRANCH.v
cp template op_BBS.v
cp template op_BIT.v
cp template op_BRK.v
cp template op_CMP.v
cp template op_CPX.v
cp template op_CPY.v
cp template op_DEC.v
cp template op_EOR.v
cp template op_INC.v
cp template op_JMP.v
cp template op_JSR.v
cp template op_LDA.v
cp template op_LDX.v
cp template op_LDY.v
cp template op_LSR.v
cp template op_ORA.v
cp template op_PHA.v
cp template op_PHP.v
cp template op_PHX.v
cp template op_PHY.v
cp template op_PLA.v
cp template op_PLP.v
cp template op_PLX.v
cp template op_PLY.v
cp template op_RMB.v
cp template op_ROL.v
cp template op_ROR.v
cp template op_RTI.v
cp template op_RTS.v
cp template op_SBC.v
cp template op_SMB.v
cp template op_STA.v
cp template op_STP.v
cp template op_STX.v
cp template op_STX.v
cp template op_STY.v
cp template op_STY.v
cp template op_STZ.v
cp template op_STZ.v
cp template op_SUB.v
cp template op_TRB.v
cp template op_TSB.v
cp template op_WAI.v

