cp template  ame_ABS_a.v # Absolute a (65832)
cp template  ame_ACC_A.v # Accumulator A (65832)
cp template  ame_AIA_A.v # Absolute Indirect (a) (65832)
cp template  ame_AIIX_A_X.v # Absolute Indexed Indirect with X (a,x) (65832)
cp template  ame_AIIY_A_y.v # Absolute Indexed Indirect with Y (a),y (65832)
cp template  ame_AIX_a_x.v # Absolute Indexed with X a,x (65832)
cp template  ame_AIY_a_y.v # Absolute Indexed with Y a,y (65832)
cp template  ame_IMM_m.v # Immediate Addressing # (65832)
cp template  ame_PCR_r.v # Program Counter Relative r (65832)
cp template  ame_STK_s.v # Stack s (65832)
