
cp template  am_ABS_a.v # Absolute a (6502)
cp template  am_ACC_A.v # Accumulator A (6502)
cp template  am_AIA_A.v # Absolute Indirect (a) (6502)
cp template  am_AIIX_A_X.v # Absolute Indexed Indirect with X (a,x) (6502)
cp template  am_AIX_a_x.v # Absolute Indexed with X a,x (6502)
cp template  am_AIY_a_y.v # Absolute Indexed with Y a,y (6502)
cp template  am_IMM_m.v # Immediate Addressing # (6502)
cp template  am_PCR_r.v # Program Counter Relative r (6502)
cp template  am_STK_s.v # Stack s (6502)
cp template  am_ZIIX_ZP_X.v # Zero Page Indexed Indirect (zp,x) (6502)
cp template  am_ZIIY_ZP_y.v # Zero Page Indirect Indexed with Y (zp),y (6502)
cp template  am_ZIX_zp_x.v # Zero Page Indexed with X zp,x (6502)
cp template  am_ZIY_zp_y.v # Zero Page Indexed with Y zp,y (6502)
cp template  am_ZPG_zp.v # Zero Page zp (6502)
cp template  am_ZPI_ZP.v # Zero Page Indirect (zp) (6502)

